# =================================================================
# MoonTV Kubernetes 密钥配置
# 版本: v4.0.0 - 企业级密钥管理
# =================================================================

apiVersion: v1
kind: Secret
metadata:
  name: moontv-secrets
  namespace: moontv
  labels:
    app.kubernetes.io/name: moontv
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: manual
  annotations:
    description: 'MoonTV application secrets'
type: Opaque
data:
  # Base64编码的密钥
  # 实际部署时应该通过kubectl create secret命令创建
  app-password: <BASE64_ENCODED_PASSWORD>
  redis-password: <BASE64_ENCODED_REDIS_PASSWORD>
  jwt-secret: <BASE64_ENCODED_JWT_SECRET>
  hmac-key: <BASE64_ENCODED_HMAC_KEY>

---
# TLS证书Secret
apiVersion: v1
kind: Secret
metadata:
  name: moontv-tls
  namespace: moontv
  labels:
    app.kubernetes.io/name: moontv
    app.kubernetes.io/component: tls
    app.kubernetes.io/managed-by: manual
  annotations:
    description: 'MoonTV TLS certificates'
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_TLS_CERT>
  tls.key: <BASE64_ENCODED_TLS_KEY>

---
# Redis认证Secret
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: moontv
  labels:
    app.kubernetes.io/name: moontv
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: manual
  annotations:
    description: 'Redis authentication credentials'
type: Opaque
data:
  password: <BASE64_ENCODED_REDIS_PASSWORD>

---
# 环境变量Secret
apiVersion: v1
kind: Secret
metadata:
  name: moontv-env-secrets
  namespace: moontv
  labels:
    app.kubernetes.io/name: moontv
    app.kubernetes.io/component: env-secrets
    app.kubernetes.io/managed-by: manual
  annotations:
    description: 'MoonTV environment variable secrets'
type: Opaque
data:
  # 数据库连接字符串
  database-url: <BASE64_ENCODED_DATABASE_URL>

  # 外部API密钥
  api-key-1: <BASE64_ENCODED_API_KEY_1>
  api-key-2: <BASE64_ENCODED_API_KEY_2>

  # 监控密钥
  sentry-dsn: <BASE64_ENCODED_SENTRY_DSN>

  # 第三方服务密钥
  upstash-url: <BASE64_ENCODED_UPSTASH_URL>
  upstash-token: <BASE64_ENCODED_UPSTASH_TOKEN>

---
# 镜像拉取Secret
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: moontv
  labels:
    app.kubernetes.io/name: moontv
    app.kubernetes.io/component: image-pull
    app.kubernetes.io/managed-by: manual
  annotations:
    description: 'GitHub Container Registry pull secret'
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG>

---
# 监控密钥
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: moontv-monitoring
  labels:
    app.kubernetes.io/name: moontv
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: manual
  annotations:
    description: 'Monitoring service secrets'
type: Opaque
data:
  grafana-admin-password: <BASE64_ENCODED_GRAFANA_PASSWORD>
  alertmanager-config: <BASE64_ENCODED_ALERTMANAGER_CONFIG>
